<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NquilinCode.Domain\NquilinCode.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.66" />
      <PackageReference Include="FluentMigrator" Version="8.0.1" />
      <PackageReference Include="FluentMigrator.Runner" Version="8.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="11.0.0-preview.1.26104.118" />
      <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.16.0" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    </ItemGroup>

</Project>
