<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\NquilinCode.Exceptions\NquilinCode.Exceptions.csproj" />
      <ProjectReference Include="..\..\Shared\NquilinCode.Kernel\NquilinCode.Kernel.csproj" />
    </ItemGroup>

</Project>
