<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\NquilinCode.Communication\NquilinCode.Communication.csproj" />
      <ProjectReference Include="..\..\Shared\NquilinCode.Exceptions\NquilinCode.Exceptions.csproj" />
      <ProjectReference Include="..\..\Shared\NquilinCode.Kernel\NquilinCode.Kernel.csproj" />
      <ProjectReference Include="..\NquilinCode.Domain\NquilinCode.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="Mapster" Version="10.0.7" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Abstractions\" />
    </ItemGroup>

</Project>
