name: SonarQube

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Instalar dotnet-sonarscanner
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      # Begin Sonar
      - name: Begin SonarQube Scan
        run: dotnet sonarscanner begin `
          /k:"Baticte_NquilinCode" `
          /o:"baticte" `
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
          /d:sonar.cs.cobertura.reportsPaths="**/coverage.cobertura.xml"
        shell: powershell
        env:
          PATH: ${{ runner.tool_cache }}/dotnet/tools:$PATH

      # Build solution
      - name: Build Solution
        run: dotnet build

      # Testar com cobertura
      - name: Run Tests with Coverage
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults

      # End Sonar
      - name: End SonarQube Scan
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        shell: powershell
