name: SonarQube

on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Instala dotnet-sonarscanner como tool global
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner
        shell: pwsh

      # Adiciona .dotnet/tools ao PATH
      - name: Add dotnet tools to PATH
        shell: pwsh
        run: $env:PATH += ";$env:USERPROFILE\.dotnet\tools"

      # Begin Sonar
      - name: Begin Sonar Scan
        shell: pwsh
        run: dotnet sonarscanner begin `
          /k:"Baticte_NquilinCode" `
          /o:"baticte" `
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
          /d:sonar.cs.cobertura.reportsPaths="**/coverage.cobertura.xml"

      # Build
      - name: Build Solution
        shell: pwsh
        run: dotnet build

      # Test + coverage
      - name: Run Tests with Coverage
        shell: pwsh
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults

      # End Sonar
      - name: End Sonar Scan
        shell: pwsh
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
